#!/bin/sh

. /lib/functions.sh

min=4
max=100

get_min_max () {
	local handler

	config_get handler $1 handler

	[ -n "$handler" -a "$handler" = "firstboot && reboot" ] && {
		config_get min $1 min
		config_get max $1 max
	}
}

logger "$BUTTON was $ACTION for $SEEN seconds"

config_load system
config_foreach get_min_max button

if [ "${ACTION}" = "released" ]
then
	/etc/init.d/ledsman stop
	/usr/sbin/led_reset_count.sh $(( $min * 1000000 / 5 )) &
	exit
fi

if [ $min -le $SEEN -a $max -ge $SEEN ];
then

	echo "FACTORY RESET" > /dev/console
	ps | grep led_reset_count.sh | awk '{print $1}' | xargs kill
	/usr/sbin/ledbar.sh blink red
	jffs2mark -y && reboot -b &
else
	echo "REBOOT" > /dev/console
	ps | grep led_reset_count.sh | awk '{print $1}' | xargs kill
	/usr/sbin/ledbar.sh blink green
	sync
	reboot -b
fi
