#!/bin/sh

. /lib/functions.sh

logger "$BUTTON was $ACTION for $SEEN seconds"

if [ "${ACTION}" = "released" ]
then
	/etc/init.d/modem stop
	/etc/init.d/ledsman restart
fi
if [ "${ACTION}" = "pressed" ]
then
        sleep 3
        /etc/init.d/modem restart
fi
