#!/bin/sh

if [ ! -f /etc/config/ntpserver ]; then
	touch /etc/config/ntpserver
	uci -q batch <<-EOF >/dev/null
	set ntpserver.general="ntpserver"
	set ntpserver.general.enabled=0
	commit ntpserver
	add ucitrack ntpserver
	set ucitrack.@ntpserver[0].init=ntpserver
	commit ucitrack
	EOF
fi

rm -f /tmp/luci-indexcache
exit 0
