#!/bin/sh /etc/rc.common

APP=/usr/sbin/modbusd

USE_PROCD=1
START=99
STOP=99

ENABLED=`uci get modbus.modbus.enabled`
PORT=`uci get modbus.modbus.port`
MAX_CONN=8

start_service() {
    if [ "$ENABLED" = "1" ]; then
	    procd_open_instance
	    procd_set_param command $APP -a 0.0.0.0 -p $PORT -m $MAX_CONN
	    procd_set_param respawn
	    procd_close_instance
	fi
}
