#!/bin/sh /etc/rc.common

# Copyright (C) 2014 Teltonika
USE_PROCD=1
START=14

BIN="/usr/sbin/operctl"
LOCKFILE="/var/run/operctl.pid"

start_service() {
	logger -t "operctl" "Deleting crontab rule"
	sed -i '/\/etc\/init.d\/operctl/d' /etc/crontabs/root
	/etc/init.d/cron restart

	logger -t "operctl" "Starting"

	procd_open_instance

	procd_set_param command "$BIN"

	procd_close_instance
}

reload_service() {
	restart
}

stop_service() {
	logger -t "operctl" "Stopping"
	rm $LOCKFILE
	# kill operchk watchdog
	ps | grep operchk.sh | awk '{print $1}' | xargs kill
}
